### ISSUE TITLE
CSSOM 阻塞 js 执行？（4-parse）

### ISSUE THREAD

**Issue by dkvirus** [alienzhou/fe-performance-journey#2]
html 代码， css 写在 header 里， js 写在 body 后面。

``` html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>测试浏览器渲染</title>
  <link rel="stylesheet" href="./assets/style.css">
</head>
<body>
  <h1>koa by html file</h1>
  <script src="./assets/script.js"></script>
  <img width="300" src="./assets/image.png">
</body>
</html>
```

服务端设置 css 文件延迟 5s 响应。Devtool 中可以看到在接受 Js 和 图片之后才接收到 css 文件以及解析 cssom。

按照 cssom 阻塞  js 执行的说法。css 写在 js 之前，但是 css 延迟响应，得等到 css 解析完成之后才会执行 js，显然不符。

![image](https://user-images.githubusercontent.com/29170168/63677139-f6668a00-c81e-11e9-8279-5cd15e59898d.png)

**Comment by alienzhou** [comment]
「cssom 阻塞 js 执行」是指阻塞 JavaScript 代码的执行，并不一定阻塞下载。
例如，在 JavaScript 中进行一些 alert 之类的操作，会等到 css 加载完毕才出现 alert 弹框。类似下面这样。
> 测试环境是  chrome 76.0

![](https://edu.bdstatic.com/v1/topic/wy36ucvBe2-1567593589760.gif)
